repos:
  - hooks:
      - args:
          - --allow-missing-credentials
        id: detect-aws-credentials
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - args:
          - --markdown-linebreak-ext=md
        id: trailing-whitespace
      - id: end-of-file-fixer
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
  - hooks:
      - id: prettier
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
  - hooks:
      - entry: codespell
        id: codespell
        language: python
        name: codespell
        types:
          - text
    repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
  - hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_checkov
      - id: terraform_docs
    repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.2
  - hooks:
      - entry:
          /bin/bash -c 'terraform providers lock -platform=windows_amd64 -platform=darwin_amd64
          -platform=linux_amd64'
        files: (.terraform.lock.hcl|version.tf)
        id: terraform-lock
        language: system
        name: terraform-lock
        types:
          - terraform
    repo: local
  - hooks:
      - entry: /bin/bash -c 'yor tag --tag-local-modules=true --directory .'
        id: yor
        language: system
        name: yor
        stages:
          - push
        types:
          - terraform
    repo: local
